### ISSUE TITLE
Session timeout in Liferay

### ISSUE THREAD

**Issue by veeras** [bluesoft-rnd/aperte-workflow-core#141]
Hi

 When we are working in Aperte Workflow after sometime LIferay session timeout is happening

In Aperte-->tomcat-->webapps-->root-->web-inf-->web.xml file the following session timeout has configured

```
    <session-config>
    <session-timeout>30</session-timeout>
</session-config>
```

Even though when we are working continuously 30 min in aperte the liferay is giving session timeout.
How to avoid this.

Thanks,
Veera

**Comment by tlipski** [comment]
that is a general issue with Vaadin & Liferay (JSR286 resource request does not refresh the session properly) . The quick fix is to disable session timeout (sometimes not recommended due to security constraints), the other thing that can be done is to add session.timeout.auto.extend=true to portal-ext.properties in Liferay's WEB-INF/classes.

But I suppose that something odd is also going on Aperte Workflow's end, so we will look into it.

**Comment by pjolszewski** [comment]
The easiest way is to extend session timeout. In order to this in tomcat conf/web.xml in session-timeout tag existing value should be replaced with bigger one i.e 600 (minutes).

According to Liferay forum value defined in tomcat' web.xml overrides that in aperteworkflow counterpart.

http://www.liferay.com/community/forums/-/message_boards/message/3390787
