### ISSUE TITLE
ConcurrentModificationException during attribute setting in Mule Step

### ISSUE THREAD

**Issue by zmalinowski** [bluesoft-rnd/aperte-workflow-core#50]
Problem occurs often, but not always. 

How to reproduce: 
- Start Reservation process (sample)
- Fill in first step (Search)
- Click continue 

Usually next click is without error.

**Comment by kdowbecki** [comment]
It looks like this problem comes from passing ProcessInstance object into a asynchronous Mule endpoint. This way there are actually two threads operation on ProcessInstance attributes, one from jBPM pool and one from Mule ESB pool. I suggest to make the endpoint synchronous, with `exchange-pattern="request-response"` (because MuseStep is utilized in synchronous way with `asynchronous=false`) or reconsider the process design.
