### ISSUE TITLE
Error in building Aperte Sourcecode

### ISSUE THREAD

**Issue by murthy516** [bluesoft-rnd/aperte-workflow-core#88]
Hi,
I downloaded source code from https://github.com/bluesoft-rnd/aperte-workflow-core.I'm trying to build using maven using mvn clean install.It is generating error as 

"ERROR] Failed to execute goal on project gui-commons: Could not resolve dependencies for project org.aperteworkflow:gui-commons:jar:1.1-SNAPSHOT: The fol
owing artifacts could not be resolved: org.vaadin.addons:customfield:jar:0.9.2, org.vaadin.addons:confirmdialog:jar:1.1.1: Failure to find org.vaadin.addo
s:customfield:jar:0.9.2 in http://repo1.maven.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval
f central has elapsed or updates are forced -> [Help 1]"

**Comment by tlipski** [comment]
Hi,

We have created a wiki page to answer this issue (and any following regarding compilation): https://github.com/bluesoft-rnd/aperte-workflow-core/wiki/Compilation-guide

**Comment by MuhammedShakir** [comment]
Hi tlipski,

I have successfully build the master with maven (Aperte 2.1 and Liferay 6.1.1). The build was successful without any errors. However when I drop userdata-widget-2.1-SNAPSHOT.jar in osgi-plugins, it gives a ClassNotFoundException for pl.net.bluesoft.rnd.pt.ext.userdata.model.ProcessInstanceUserAssignment. 

Further it says org.osgi.framework.BundleException: Unresolved constraint in bundle pl.net.bluesoft.rnd.pt.ext.userdata [1]: Unable to resolve 1.1: missing requirement [1.1] osgi.wiring.package; (&(osgi.wiring.package=com.liferay.portal.model)(version>=6.1.0))

This is the only component that fails. I will high appreciate any help.

Best Regards

**Comment by kkolodziej** [comment]
Hi 
Sorry for late answer,
Do you still have problems with userData widget and modeler on liferay  6.1?
I am asking because i noticed your recent activity on Rupals blog.

As for "userdata-widget": It's providing users list from liferay database. (https://github.com/bluesoft-rnd/aperte-workflow-core/wiki/Liferay-UserData-Widget), and it was designed for 6.0 version. Because 6.1 version had some changes in interfacess, the error is nothing surprising. 
But, I thing that some minor changes in: pl.net.bluesoft.rnd.pt.ext.userdata.widget.LiferayUserDataWidget, should do the work.

Regardless of that, this widget is not crucial to aperteworkflow, so  if you don't care, lack of user list in process, just throw it away.

Still if you have more questions or doubts, fell free to ask.

Regards
Kamil

**Comment by MuhammedShakir** [comment]
Hi Kamil,

Nice to receive this message from you. Well..... I downloaded the user widget 2.0 from GitHub and placed the same in OSGi and it worked. However got into problems with VAADIN components. It shows error in tree view format on the web page after I start a process for components like context help and flex option.......component. Can any one of you offer paid service where you setup Aperte 2.x on Liferay 6.1.1. It must work without any errors of any kind with all features and working sample Liferay Symposium process. Note that I have successfully setup the modeler on 6.1.1 and it works like a charm.
